/* sfcall.c: generated by interface compiler */

#include "sfcall.h"


extern unsigned long long displaySimLtime(int tu, int tp);
extern unsigned displaySimStime(int tu, int tp);

static unsigned long long getLtime(int tu, int tp);

static void Bv2Lvx(iscLv_t *lv, char *bv, int nbytes) {
  int i = 0;
  for (i = 0; nbytes >= 4; i++) {
    memcpy(&(lv[i].a), bv, 4);
    nbytes -= 4; bv += 4;
    lv[i].b = 0;
  }
  if (nbytes) {
    lv[i].a = 0;
    memcpy(&(lv[i].a), bv, nbytes);
    lv[i].b = 0;
  }
}
static void Lv2Bvx(char *bv, iscLv_t *lv, int nbytes) {
  unsigned v;
  int i = 0;
  for (i = 0; nbytes >= 4; i++) {
    v = lv[i].a & ~lv[i].b;
    memcpy(bv, &v, 4);
    nbytes -= 4; bv += 4;
  }
  if (nbytes) {
    v = lv[i].a & ~lv[i].b;
    memcpy(bv, &v, nbytes);
  }
}
static void Mbuf2Bv(char *bv, char *mbuf, int nbytes, int width, int exp) {
  bzero((void *) bv, nbytes);
  int ndestbytes = (width+31)/32 * 4;
  int nsrcbytes = (width+7)/8;
  char *destptr = bv;
  char *srcptr = mbuf;
  int cbytes = 0;
  while (cbytes < nbytes) {
    bzero((void *) destptr, ndestbytes);
    memcpy(destptr, srcptr, nsrcbytes);
    destptr += ndestbytes;
    srcptr += nsrcbytes;
    if (exp) cbytes += ndestbytes; else cbytes += nsrcbytes;
  }
}
static void Bv2Mbuf(char *mbuf, char *bv, int nbytes, int width, int exp) {
  int ndestbytes = (width+7)/8;
  int nsrcbytes = (width+31)/32 * 4;
  char *srcptr = bv;
  char *destptr = mbuf;
  int cbytes = 0;
  while (cbytes < nbytes) {
    memcpy(destptr, srcptr, ndestbytes);
    destptr += ndestbytes;
    srcptr += nsrcbytes;
    if (exp) cbytes += nsrcbytes; else cbytes += ndestbytes;
  }
}


#ifdef __cplusplus
extern "C" {
#endif


#ifdef __cplusplus
}
#endif

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif
