xc_work/v/12.v
xc_work/v/2.sv
xc_work/v/3.sv
xc_work/v/4.sv
xc_work/v/5.sv
xc_work/v/6.sv
xc_work/v/7.sv
xc_work/v/8.sv
xc_work/v/9.sv
xc_work/v/10.sv
xc_work/v/11.sv
/tools/cadence/UXE171_p98/tools.lnx86/etc/ixcom/xcva_prims_pdsa.v
/tools/cadence/UXE171_p98/tools.lnx86/etc/ixcom/xcva_prims_ice.v
xc_work/v/xcva_top.v
