
## hdl2qtdb starts at 03/07/2020 15:38:16 tang_dx V17.1.0, PID: 151041 (pld615)
hdl2qtdb 6 9
## 64bit program from /tools/cadence/UXE171_p98/tools.lnx86/bin on Linux 2.6.32-696.el6.x86_64 64bit
(c) 1991-2017 Cadence Design Systems, Inc. All rights reserved worldwide.
See files in <rootdir>/share/uxe/install/Copyrights
#)libmcp.so - UXE, V17.1.0
#)libimport.so - UXE, V17.1.0.p98
#)libdataStruct.so - UXE, V17.1.0
#)libdbgutil.so - UXE, V17.1.0.p98
#)libhdlmap.so - UXE, V17.1.0
#)libqt.so - UXE, V17.1.0.p98
#)libqtutil.so - UXE, V17.1.0
#)libsd.so - UXE, V17.1.0.p98
* System parameters:
vm/overcommit_memory: 0
vm/overcommit_ratio: 50
vm/oom_dump_tasks: 1
vm/oom_kill_allocating_task: 0
* System info:
% free -m
             total       used       free     shared    buffers     cached
Mem:        257959      24948     233011         29        546      20250
-/+ buffers/cache:       4151     253808
Swap:         4095          0       4095
* System info:
% free -m
             total       used       free     shared    buffers     cached
Mem:        257959      25271     232688         29        546      20252
-/+ buffers/cache:       4472     253487
Swap:         4095          0       4095
## hdl2qtdb exits at 03/07/2020 15:38:17 Status: 0, PID: 151041
## hdl2qtdb Elapsed time: 0:00:01, CPU time: 0:00:00.21, Memory Usage: 2.2G
## Child Proc. CPU time: 0:00:00.07

## hdl2qtdb starts at 03/07/2020 15:38:17 tang_dx V17.1.0, PID: 151173 (pld615)
hdl2qtdb 6 9
## 64bit program from /tools/cadence/UXE171_p98/tools.lnx86/bin on Linux 2.6.32-696.el6.x86_64 64bit
(c) 1991-2017 Cadence Design Systems, Inc. All rights reserved worldwide.
See files in <rootdir>/share/uxe/install/Copyrights
#)libmcp.so - UXE, V17.1.0
#)libimport.so - UXE, V17.1.0.p98
#)libdataStruct.so - UXE, V17.1.0
#)libdbgutil.so - UXE, V17.1.0.p98
#)libhdlmap.so - UXE, V17.1.0
#)libqt.so - UXE, V17.1.0.p98
#)libqtutil.so - UXE, V17.1.0
#)libsd.so - UXE, V17.1.0.p98
* System parameters:
vm/overcommit_memory: 0
vm/overcommit_ratio: 50
vm/oom_dump_tasks: 1
vm/oom_kill_allocating_task: 0
* System info:
% free -m
             total       used       free     shared    buffers     cached
Mem:        257959      24936     233023         29        546      20254
-/+ buffers/cache:       4135     253824
Swap:         4095          0       4095
* System info:
% free -m
             total       used       free     shared    buffers     cached
Mem:        257959      25249     232710         29        546      20256
-/+ buffers/cache:       4446     253513
Swap:         4095          0       4095
## hdl2qtdb exits at 03/07/2020 15:38:17 Status: 0, PID: 151173
## hdl2qtdb Elapsed time: 0:00:00, CPU time: 0:00:00.19, Memory Usage: 2.2G
## Child Proc. CPU time: 0:00:00.06

## hdl2qtdb starts at 03/07/2020 15:38:18 tang_dx V17.1.0, PID: 151357 (pld615)
hdl2qtdb 6 9
## 64bit program from /tools/cadence/UXE171_p98/tools.lnx86/bin on Linux 2.6.32-696.el6.x86_64 64bit
(c) 1991-2017 Cadence Design Systems, Inc. All rights reserved worldwide.
See files in <rootdir>/share/uxe/install/Copyrights
#)libmcp.so - UXE, V17.1.0
#)libimport.so - UXE, V17.1.0.p98
#)libdataStruct.so - UXE, V17.1.0
#)libdbgutil.so - UXE, V17.1.0.p98
#)libhdlmap.so - UXE, V17.1.0
#)libqt.so - UXE, V17.1.0.p98
#)libqtutil.so - UXE, V17.1.0
#)libsd.so - UXE, V17.1.0.p98
* System parameters:
vm/overcommit_memory: 0
vm/overcommit_ratio: 50
vm/oom_dump_tasks: 1
vm/oom_kill_allocating_task: 0
* System info:
% free -m
             total       used       free     shared    buffers     cached
Mem:        257959      24944     233015         29        546      20256
-/+ buffers/cache:       4140     253819
Swap:         4095          0       4095
* System info:
% free -m
             total       used       free     shared    buffers     cached
Mem:        257959      25255     232704         29        546      20256
-/+ buffers/cache:       4451     253508
Swap:         4095          0       4095
## hdl2qtdb exits at 03/07/2020 15:38:18 Status: 0, PID: 151357
## hdl2qtdb Elapsed time: 0:00:00, CPU time: 0:00:00.13, Memory Usage: 2.2G
## Child Proc. CPU time: 0:00:00.06

## xeCompile starts at 03/07/2020 15:38:18 tang_dx V17.1.0.p98, PID: 151477 (pld615)
xeCompile /tools/cadence/UXE171_p98/tools.lnx86/etc/qel/ixcom.qel
## 64bit program from /tools/cadence/UXE171_p98/tools.lnx86/bin on Linux 2.6.32-696.el6.x86_64 64bit
(c) 1991-2017 Cadence Design Systems, Inc. All rights reserved worldwide.
See files in <rootdir>/share/uxe/install/Copyrights
#)libhdl.so - UXE, V17.1.0
#)libhdlmap.so - UXE, V17.1.0
#)libimp.so - UXE, V17.1.0
#)libdataStruct.so - UXE, V17.1.0
#)libudq.so - UXE, V17.1.0.p98
#)liboptutil.so - UXE, V17.1.0
#)libpich.so - UXE, V17.1.0
#)libtich.so - UXE, V17.1.0.p98
#)libcmp.so - UXE, V17.1.0.p21
#)libddb.so - UXE, V17.1.0
#)libudp.so - UXE, V17.1.0.p98
#)libPDBCommands.so - UXE, V17.1.0
#)libhwConfig.so - UXE, V17.1.0
#)libCompilerRT.so - UXE, V17.1.0.p98
#)libclkBDD.a - UXE, V17.1.0.p98
#)libsdltm.so - UXE, V17.1.0.p98
#)libet3compile.so - UXE, V17.1.0
#)libdb2util.so - UXE, V17.1.0
#)liboptutil.so - UXE, V17.1.0
#)libet3wrapper.so - UXE, V17.1.0
#)libsideFile.so - UXE, V17.1.0.p98
#)libdbgPrepare.so - UXE, V17.1.0.p98
#)libucdbwrt.so - UXE, V17.1.0
#)libucdb_sh.so - UXE, V17.1.0
#)librppconfig.so - UXE, V17.1.0
#)libeclutil.so - UXE, V17.1.0.p98
#)libqtutil.so - UXE, V17.1.0
#)libdbgutil.so - UXE, V17.1.0.p98
#)libuxeenglic.so - UXE, V17.1.0
#)libtcl.so - UXE, V17.1.0.p98
#)libtk.so - UXE, V17.1.0.p98
#)libblt.so - UXE, V17.1.0.p98
#)libtix.so - UXE, V17.1.0.p98
#)libqt.so - UXE, V17.1.0.p98
#)libqtutil.so - UXE, V17.1.0
#)libsd.so - UXE, V17.1.0.p98
* System parameters:
vm/overcommit_memory: 0
vm/overcommit_ratio: 50
vm/oom_dump_tasks: 1
vm/oom_kill_allocating_task: 0
* System info:
% free -m
             total       used       free     shared    buffers     cached
Mem:        257959      24942     233017         29        546      20257
-/+ buffers/cache:       4137     253822
Swap:         4095          0       4095
WARNING (legacy-52177): There is no remote shell in your path.
Check the value of XE_SECURE_CONNECTION and your OS environment.
WARNING (legacy-52368): Current overcommit memory settings are not optimal. The values are (memory=0, ratio=50). Suggested \
values are (memory=2, ratio=100).
XEC> #
XEC> # Backend compiler script for ixcom 
XEC> #
XEC> 
XEC> # Source custom compile script from user if specified
XEC> set compileQel "xc_work/qel/compile.qel"
xc_work/qel/compile.qel
XEC> if { [file exists $compileQel] } {
    source $compileQel
    exit
} else {
    if {[file exists compile.qel]} {
	source compile.qel
	exit
    }
}
XEC> 
XEC> source [file join $env(QTHOME) etc qel ixcom_util.qel]
XEC> 
XEC> set skipImportScript "xc_work/qel/skipImport.qel"
xc_work/qel/skipImport.qel
XEC> # Skip import if skipImportScript exists
XEC> if { [file exists $skipImportScript] != 1} {
    set importScript "xc_work/qel/import.qel"
    if { [file exists $importScript] } {
        source $importScript
    } else {
	if {[file exists xc_work/nl/refLib.qel]} {
	    # External netlist compile, source reference library list
	    source xc_work/nl/refLib.qel
	} else {
	    if {[file exists refLib.qel]} {
		source refLib.qel
	    } else {
		refLib qtref generic
	    }
	}
	
	# design -rm
	importOption {mode full}
	importOption {special DELETE_LIBS_ON_FULL}
	importOption {library hdldb}
	importOption {V1995 ON}
	if {[file exists xc_work/nl/import.qel]} {
	    # External netlist compile, source IXCOM created import script
	    source xc_work/nl/import.qel
	} else {
	    importOption {IXCOM_RTL ON}
	    netlistFile {verilog xc_work/xc_va.ver}
	    set externalNetlistsQel "xc_work/qel/externalNetlists.qel"
	    if {[file exists $externalNetlistsQel]} {
		source $externalNetlistsQel
	    } else {
		if {[file exists externalNetlists.qel]} {
		    source externalNetlists.qel
		}
	    }
	}

        set gfifoSynthBypassQel "xc_work/qel/gfifo_synth_bypass.qel"
        if { [file exists $gfifoSynthBypassQel] } {
            # Compile gfifo related logic that has been bypassed around hdlice.
            source $gfifoSynthBypassQel
        }

        set scgGfifoSynthBypassQel "xc_work/qel/scg_gfifo_synth_bypass.qel"
        if { [file exists $scgGfifoSynthBypassQel] } {
            # Compile scg-gfifo related logic that has been bypassed around hdlice.
            source $scgGfifoSynthBypassQel
        }

        set sfifoSynthBypassQel "xc_work/qel/sfifo_synth_bypass.qel"
        if { [file exists $sfifoSynthBypassQel] } {
            # Compile sfifo related logic that has been bypassed around hdlice.
            source $sfifoSynthBypassQel
        }

        set ifSynSynthBypassQel "xc_work/qel/ifsyn_synth_bypass.qel"
        if { [file exists $ifSynSynthBypassQel] } {
            # Compile ifsyn related logic that has been bypassed around hdlice.
            source $ifSynSynthBypassQel
        }

	designImport

	set postImportScript "xc_work/qel/postImport.qel"
	if { [file exists $postImportScript] } {
	    source $postImportScript
	}
    }
}

## import starts at 03/07/2020 15:38:18 tang_dx V17.1.0.p98, PID: 151544 (pld615)
import -qel -qp 0 -o .xeimp.mdl .xeimp.dil
## 64bit program from /tools/cadence/UXE171_p98/tools.lnx86/bin on Linux 2.6.32-696.el6.x86_64 64bit
(c) 1991-2017 Cadence Design Systems, Inc. All rights reserved worldwide.
See files in <rootdir>/share/uxe/install/Copyrights
#)libimport.so - UXE, V17.1.0.p98
#)libmcp.so - UXE, V17.1.0
#)libdataStruct.so - UXE, V17.1.0
#)libhdlmap.so - UXE, V17.1.0
#)libqt.so - UXE, V17.1.0.p98
#)libqtutil.so - UXE, V17.1.0
#)libsd.so - UXE, V17.1.0.p98
* System parameters:
vm/overcommit_memory: 0
vm/overcommit_ratio: 50
vm/oom_dump_tasks: 1
vm/oom_kill_allocating_task: 0
* System info:
% free -m
import - UXE, V17.1.0.p98
             total       used       free     shared    buffers     cached
Mem:        257959      25188     232771         29        546      20257
-/+ buffers/cache:       4384     253575
Swap:         4095          0       4095
INFO (import-1038): Processing import control information from file .xeimp.dil.
INFO (import-1228): Name scope processing is not needed.
INFO (import-1022): Accessing netlist file xc_work/xc_va.ver to create components and terminals.
INFO (import-1022): Accessing netlist file xc_work/xc_va.ver to create instances and nets.
INFO (import-1028): Library hdldb, cell IXC_OSF1 contains no instances.
INFO (import-1028): Library hdldb, cell IXC_OSF contains no instances.
INFO (import-1028): Library hdldb, cell _ixc_isc contains no instances.
INFO (import-1028): Library hdldb, cell IXC_ISF contains no instances.
INFO (mcp-1603): No new memory definition detected by automatic memory detection.
* System info:
INFO (import-1246): Netlist File xc_work/xc_va.ver (VERILOG) Summary:
     Lines parsed: 2323
     Cells created: 22
     Cells deleted: 0
     Cells compared: 0
     Terminals created: 258
     Terminals deleted: 0
     Instances created: 1831
     Instances deleted: 0
     Nets created: 22029
     Nets deleted: 0
     Connections created: 3674
     Connections deleted: 0
INFO (import-1245): Import Summary:
     Lines parsed: 2323
     Cells created: 22
     Cells deleted: 0
     Cells compared: 0
     Terminals created: 258
     Terminals deleted: 0
     Instances created: 1831
     Instances deleted: 0
     Nets created: 22029
     Nets deleted: 0
     Connections created: 3674
     Connections deleted: 0
INFO (import-1054): exit SUCCESS.
% free -m
             total       used       free     shared    buffers     cached
Mem:        257959      25514     232445         29        546      20258
-/+ buffers/cache:       4709     253250
Swap:         4095          0       4095
## import exits at 03/07/2020 15:38:19 Status: 0, PID: 151544
## import Elapsed time: 0:00:01, CPU time: 0:00:00.24, Memory Usage: 2.3G
## Child Proc. CPU time: 0:00:00.08
INFO (legacy-11003): import FINISHED SUCCESSFULLY
XEC> 
XEC> set importOnly "xc_work/qel/importOnly.qel"
xc_work/qel/importOnly.qel
XEC>    if { [file exists $importOnly] == 1 } {
        exit
}
XEC> 
XEC> design hdldb xcva_top

## oomr starts at 03/07/2020 15:38:19 tang_dx V17.1.0.p98, PID: 151612 (pld615)
oomr hdldb xcva_top
## 64bit program from /tools/cadence/UXE171_p98/tools.lnx86/bin on Linux 2.6.32-696.el6.x86_64 64bit
(c) 1991-2017 Cadence Design Systems, Inc. All rights reserved worldwide.
See files in <rootdir>/share/uxe/install/Copyrights
#)libimport.so - UXE, V17.1.0.p98
#)libmcp.so - UXE, V17.1.0
#)libdataStruct.so - UXE, V17.1.0
#)libhdlmap.so - UXE, V17.1.0
#)libqt.so - UXE, V17.1.0.p98
#)libqtutil.so - UXE, V17.1.0
#)libsd.so - UXE, V17.1.0.p98
* System parameters:
vm/overcommit_memory: 0
vm/overcommit_ratio: 50
vm/oom_dump_tasks: 1
vm/oom_kill_allocating_task: 0
* System info:
% free -m
             total       used       free     shared    buffers     cached
Mem:        257959      25190     232769         29        546      20258
-/+ buffers/cache:       4385     253574
Swap:         4095          0       4095
* System info:
% free -m
             total       used       free     shared    buffers     cached
Mem:        257959      25189     232770         29        546      20258
-/+ buffers/cache:       4384     253575
Swap:         4095          0       4095
## oomr exits at 03/07/2020 15:38:19 Status: 0, PID: 151612
## oomr Elapsed time: 0:00:00, CPU time: 0:00:00.04, Memory Usage: 1.8G
## Child Proc. CPU time: 0:00:00.08
Import library "hdldb"
Import library "qtref"
QTDB Library "qtref" has been imported successfully
QTDB Library "hdldb" has been imported successfully
hdldb xcva_top
XEC> 
XEC> memoryTransform -add {* SHALLOW off }
XEC> compilerOption -add {mode ice}
XEC> precompileOption -add {keepEmptyCells}
XEC> precompileOption -add {breakECMloops}
XEC> precompileOption -add dontMergeCommon
XEC> probeInternalNet -add xc_top.sdlEnable xc_top.tbcEnable xc_top.sdlHaltHwClk xc_top.hwClkDbg xc_top.hwClkDbgTime \
xc_top.hwClkEnable
WARNING (legacy-49196): Run 'emulatorConfiguration' command first.
WARNING (legacy-49196): Run 'emulatorConfiguration' command first.
WARNING (legacy-49196): Run 'emulatorConfiguration' command first.
WARNING (legacy-49196): Run 'emulatorConfiguration' command first.
WARNING (legacy-49196): Run 'emulatorConfiguration' command first.
WARNING (legacy-49196): Run 'emulatorConfiguration' command first.
XEC> set compileScript "compile -names_crit"
compile -names_crit
XEC> set postCompileScript ""
XEC> 
XEC> handleBackendArgs $argc $argv
XEC> 
XEC> set defaultConfg [ file join $env(QTHOME) etc et3 ua_default.et3confg ]
/tools/cadence/UXE171_p98/tools.lnx86/etc/et3/ua_default.et3confg
XEC> emulatorConfiguration -add "file $defaultConfg" "boards 0.1"
/bin/cp -f /tools/cadence/UXE171_p98/tools.lnx86/etc/et3/ua_default.et3confg dbFiles/xcva_top.et3confg
XEC> 
XEC> if {[file exists xc_work/nl/hot-swap.qel]} {
    source xc_work/nl/hot-swap.qel
}
XEC> 
XEC> # Source compiler options script from user if specified
XEC> set compilerOptionsQel "xc_work/qel/compilerOptions.qel"
xc_work/qel/compilerOptions.qel
XEC> if { [file exists $compilerOptionsQel] } {
    source $compilerOptionsQel
} else {
    if {[file exists compilerOptions.qel]} {
	source compilerOptions.qel
    }
}
XEC> 
XEC> if {[info exists env(XE_DYNP)]} {
    compilerOption -add {visionMode DYNP}
} elseif {[info exists env(UXE_DYNP)]} {
    compilerOption -add {visionMode DYNP}
}
XEC> 
XEC> 
XEC> if {[info exists env(XE_MINSTEP)]} {
  eval "compilerOption -add {minStep $env(XE_MINSTEP)}"
} elseif  {[info exists env(UXE_MINSTEP)]} {
  eval "compilerOption -add {minStep $env(UXE_MINSTEP)}"
}
XEC> 
XEC> 
XEC> checkEnvForHostSetup
Environment variables found for emulator configuration.
emulatorConfiguration -add {host /tools/cadence/UXE171_p98/tools.lnx86} {boards 0.0}
WARNING (legacy-0): Can't resolve remote hostname 
/usr/bin/rcp /tools/cadence/UXE171_p98/tools.lnx86:/et3mach//tools/cadence/UXE171_p98/tools.lnx86.et3confg \
dbFiles/xcva_top.et3confg
ERROR (legacy-49382): Cannot copy \
'/tools/cadence/UXE171_p98/tools.lnx86:/et3mach//tools/cadence/UXE171_p98/tools.lnx86.et3confg': ÿÿ.
ERROR (legacy-43702): Failed to add emulator configuration.

    while executing
"emulatorConfiguration -add {host /tools/cadence/UXE171_p98/tools.lnx86} {boards 0.0}"
    ("eval" body line 1)
    invoked from within
"eval $cfgcmd "
    (procedure "checkEnvForHostSetup" line 35)
    invoked from within
"checkEnvForHostSetup"
    (file "/tools/cadence/UXE171_p98/tools.lnx86/etc/qel/ixcom.qel" line 140)
## xeCompile exits at 03/07/2020 15:38:19 Status: 1, PID: 151477
## xeCompile Elapsed time: 0:00:01, CPU time: 0:00:00.32, Memory Usage: 1.5G
## Child Proc. CPU time: 0:00:00.56

## xeCompile starts at 03/07/2020 16:41:34 tang_dx V17.1.0.p98, PID: 153901 (pld615)
xeCompile /tools/cadence/UXE171_p98/tools.lnx86/etc/qel/ixcom.qel
## 64bit program from /tools/cadence/UXE171_p98/tools.lnx86/bin on Linux 2.6.32-696.el6.x86_64 64bit
(c) 1991-2017 Cadence Design Systems, Inc. All rights reserved worldwide.
See files in <rootdir>/share/uxe/install/Copyrights
#)libhdl.so - UXE, V17.1.0
#)libhdlmap.so - UXE, V17.1.0
#)libimp.so - UXE, V17.1.0
#)libdataStruct.so - UXE, V17.1.0
#)libudq.so - UXE, V17.1.0.p98
#)liboptutil.so - UXE, V17.1.0
#)libpich.so - UXE, V17.1.0
#)libtich.so - UXE, V17.1.0.p98
#)libcmp.so - UXE, V17.1.0.p21
#)libddb.so - UXE, V17.1.0
#)libudp.so - UXE, V17.1.0.p98
#)libPDBCommands.so - UXE, V17.1.0
#)libhwConfig.so - UXE, V17.1.0
#)libCompilerRT.so - UXE, V17.1.0.p98
#)libclkBDD.a - UXE, V17.1.0.p98
#)libsdltm.so - UXE, V17.1.0.p98
#)libet3compile.so - UXE, V17.1.0
#)libdb2util.so - UXE, V17.1.0
#)liboptutil.so - UXE, V17.1.0
#)libet3wrapper.so - UXE, V17.1.0
#)libsideFile.so - UXE, V17.1.0.p98
#)libdbgPrepare.so - UXE, V17.1.0.p98
#)libucdbwrt.so - UXE, V17.1.0
#)libucdb_sh.so - UXE, V17.1.0
#)librppconfig.so - UXE, V17.1.0
#)libeclutil.so - UXE, V17.1.0.p98
#)libqtutil.so - UXE, V17.1.0
#)libdbgutil.so - UXE, V17.1.0.p98
#)libuxeenglic.so - UXE, V17.1.0
#)libtcl.so - UXE, V17.1.0.p98
#)libtk.so - UXE, V17.1.0.p98
#)libblt.so - UXE, V17.1.0.p98
#)libtix.so - UXE, V17.1.0.p98
#)libqt.so - UXE, V17.1.0.p98
#)libqtutil.so - UXE, V17.1.0
#)libsd.so - UXE, V17.1.0.p98
* System parameters:
vm/overcommit_memory: 0
vm/overcommit_ratio: 50
vm/oom_dump_tasks: 1
vm/oom_kill_allocating_task: 0
* System info:
% free -m
             total       used       free     shared    buffers     cached
Mem:        257959      24946     233013         29        547      20259
-/+ buffers/cache:       4140     253819
Swap:         4095          0       4095
WARNING (legacy-52177): There is no remote shell in your path.
Check the value of XE_SECURE_CONNECTION and your OS environment.
WARNING (legacy-52368): Current overcommit memory settings are not optimal. The values are (memory=0, ratio=50). Suggested \
values are (memory=2, ratio=100).
XEC> #
XEC> # Backend compiler script for ixcom 
XEC> #
XEC> 
XEC> # Source custom compile script from user if specified
XEC> set compileQel "xc_work/qel/compile.qel"
xc_work/qel/compile.qel
XEC> if { [file exists $compileQel] } {
    source $compileQel
    exit
} else {
    if {[file exists compile.qel]} {
	source compile.qel
	exit
    }
}
XEC> 
XEC> source [file join $env(QTHOME) etc qel ixcom_util.qel]
XEC> 
XEC> set skipImportScript "xc_work/qel/skipImport.qel"
xc_work/qel/skipImport.qel
XEC> # Skip import if skipImportScript exists
XEC> if { [file exists $skipImportScript] != 1} {
    set importScript "xc_work/qel/import.qel"
    if { [file exists $importScript] } {
        source $importScript
    } else {
	if {[file exists xc_work/nl/refLib.qel]} {
	    # External netlist compile, source reference library list
	    source xc_work/nl/refLib.qel
	} else {
	    if {[file exists refLib.qel]} {
		source refLib.qel
	    } else {
		refLib qtref generic
	    }
	}
	
	# design -rm
	importOption {mode full}
	importOption {special DELETE_LIBS_ON_FULL}
	importOption {library hdldb}
	importOption {V1995 ON}
	if {[file exists xc_work/nl/import.qel]} {
	    # External netlist compile, source IXCOM created import script
	    source xc_work/nl/import.qel
	} else {
	    importOption {IXCOM_RTL ON}
	    netlistFile {verilog xc_work/xc_va.ver}
	    set externalNetlistsQel "xc_work/qel/externalNetlists.qel"
	    if {[file exists $externalNetlistsQel]} {
		source $externalNetlistsQel
	    } else {
		if {[file exists externalNetlists.qel]} {
		    source externalNetlists.qel
		}
	    }
	}

        set gfifoSynthBypassQel "xc_work/qel/gfifo_synth_bypass.qel"
        if { [file exists $gfifoSynthBypassQel] } {
            # Compile gfifo related logic that has been bypassed around hdlice.
            source $gfifoSynthBypassQel
        }

        set scgGfifoSynthBypassQel "xc_work/qel/scg_gfifo_synth_bypass.qel"
        if { [file exists $scgGfifoSynthBypassQel] } {
            # Compile scg-gfifo related logic that has been bypassed around hdlice.
            source $scgGfifoSynthBypassQel
        }

        set sfifoSynthBypassQel "xc_work/qel/sfifo_synth_bypass.qel"
        if { [file exists $sfifoSynthBypassQel] } {
            # Compile sfifo related logic that has been bypassed around hdlice.
            source $sfifoSynthBypassQel
        }

        set ifSynSynthBypassQel "xc_work/qel/ifsyn_synth_bypass.qel"
        if { [file exists $ifSynSynthBypassQel] } {
            # Compile ifsyn related logic that has been bypassed around hdlice.
            source $ifSynSynthBypassQel
        }

	designImport

	set postImportScript "xc_work/qel/postImport.qel"
	if { [file exists $postImportScript] } {
	    source $postImportScript
	}
    }
}

## import starts at 03/07/2020 16:41:35 tang_dx V17.1.0.p98, PID: 153968 (pld615)
import -qel -qp 0 -o .xeimp.mdl .xeimp.dil
## 64bit program from /tools/cadence/UXE171_p98/tools.lnx86/bin on Linux 2.6.32-696.el6.x86_64 64bit
(c) 1991-2017 Cadence Design Systems, Inc. All rights reserved worldwide.
See files in <rootdir>/share/uxe/install/Copyrights
#)libimport.so - UXE, V17.1.0.p98
#)libmcp.so - UXE, V17.1.0
#)libdataStruct.so - UXE, V17.1.0
#)libhdlmap.so - UXE, V17.1.0
#)libqt.so - UXE, V17.1.0.p98
#)libqtutil.so - UXE, V17.1.0
#)libsd.so - UXE, V17.1.0.p98
* System parameters:
vm/overcommit_memory: 0
vm/overcommit_ratio: 50
vm/oom_dump_tasks: 1
vm/oom_kill_allocating_task: 0
* System info:
% free -m
import - UXE, V17.1.0.p98
             total       used       free     shared    buffers     cached
Mem:        257959      25191     232768         29        547      20259
-/+ buffers/cache:       4384     253575
Swap:         4095          0       4095
INFO (import-1038): Processing import control information from file .xeimp.dil.
INFO (import-1228): Name scope processing is not needed.
INFO (import-1022): Accessing netlist file xc_work/xc_va.ver to create components and terminals.
INFO (import-1022): Accessing netlist file xc_work/xc_va.ver to create instances and nets.
INFO (import-1028): Library hdldb, cell IXC_ISF contains no instances.
INFO (import-1028): Library hdldb, cell IXC_OSF1 contains no instances.
INFO (import-1028): Library hdldb, cell _ixc_isc contains no instances.
INFO (import-1028): Library hdldb, cell IXC_OSF contains no instances.
INFO (mcp-1603): No new memory definition detected by automatic memory detection.
* System info:
INFO (import-1246): Netlist File xc_work/xc_va.ver (VERILOG) Summary:
     Lines parsed: 2323
     Cells created: 22
     Cells deleted: 0
     Cells compared: 0
     Terminals created: 258
     Terminals deleted: 0
     Instances created: 1831
     Instances deleted: 0
     Nets created: 22029
     Nets deleted: 0
     Connections created: 3674
     Connections deleted: 0
INFO (import-1245): Import Summary:
     Lines parsed: 2323
     Cells created: 22
     Cells deleted: 0
     Cells compared: 0
     Terminals created: 258
     Terminals deleted: 0
     Instances created: 1831
     Instances deleted: 0
     Nets created: 22029
     Nets deleted: 0
     Connections created: 3674
     Connections deleted: 0
INFO (import-1054): exit SUCCESS.
% free -m
             total       used       free     shared    buffers     cached
Mem:        257959      25516     232443         29        547      20259
-/+ buffers/cache:       4709     253250
Swap:         4095          0       4095
## import exits at 03/07/2020 16:41:35 Status: 0, PID: 153968
## import Elapsed time: 0:00:00, CPU time: 0:00:00.23, Memory Usage: 2.3G
## Child Proc. CPU time: 0:00:00.08
INFO (legacy-11003): import FINISHED SUCCESSFULLY
XEC> 
XEC> set importOnly "xc_work/qel/importOnly.qel"
xc_work/qel/importOnly.qel
XEC>    if { [file exists $importOnly] == 1 } {
        exit
}
XEC> 
XEC> design hdldb xcva_top

## oomr starts at 03/07/2020 16:41:35 tang_dx V17.1.0.p98, PID: 154035 (pld615)
oomr hdldb xcva_top
## 64bit program from /tools/cadence/UXE171_p98/tools.lnx86/bin on Linux 2.6.32-696.el6.x86_64 64bit
(c) 1991-2017 Cadence Design Systems, Inc. All rights reserved worldwide.
See files in <rootdir>/share/uxe/install/Copyrights
#)libimport.so - UXE, V17.1.0.p98
#)libmcp.so - UXE, V17.1.0
#)libdataStruct.so - UXE, V17.1.0
#)libhdlmap.so - UXE, V17.1.0
#)libqt.so - UXE, V17.1.0.p98
#)libqtutil.so - UXE, V17.1.0
#)libsd.so - UXE, V17.1.0.p98
* System parameters:
vm/overcommit_memory: 0
vm/overcommit_ratio: 50
vm/oom_dump_tasks: 1
vm/oom_kill_allocating_task: 0
* System info:
% free -m
             total       used       free     shared    buffers     cached
Mem:        257959      25193     232766         29        547      20259
-/+ buffers/cache:       4387     253572
Swap:         4095          0       4095
* System info:
% free -m
             total       used       free     shared    buffers     cached
Mem:        257959      25193     232766         29        547      20259
-/+ buffers/cache:       4387     253572
Swap:         4095          0       4095
## oomr exits at 03/07/2020 16:41:35 Status: 0, PID: 154035
## oomr Elapsed time: 0:00:00, CPU time: 0:00:00.04, Memory Usage: 1.8G
## Child Proc. CPU time: 0:00:00.07
Import library "hdldb"
Import library "qtref"
QTDB Library "qtref" has been imported successfully
QTDB Library "hdldb" has been imported successfully
hdldb xcva_top
XEC> 
XEC> memoryTransform -add {* SHALLOW off }
INFO (legacy-22706): '* shallow off' of 'memoryTransform' is already in the DB.
XEC> compilerOption -add {mode ice}
XEC> precompileOption -add {keepEmptyCells}
INFO (legacy-47291): Precompile option keepEmptyCells is already in the DB.
XEC> precompileOption -add {breakECMloops}
INFO (legacy-47291): Precompile option breakECMloops is already in the DB.
XEC> precompileOption -add dontMergeCommon
INFO (legacy-47291): Precompile option dontMergeCommon is already in the DB.
XEC> probeInternalNet -add xc_top.sdlEnable xc_top.tbcEnable xc_top.sdlHaltHwClk xc_top.hwClkDbg xc_top.hwClkDbgTime \
xc_top.hwClkEnable
WARNING (legacy-49196): Run 'emulatorConfiguration' command first.
INFO (legacy-42185): probeInternalNet name xc_top.sdlEnable is already in the DB.
WARNING (legacy-49196): Run 'emulatorConfiguration' command first.
INFO (legacy-42185): probeInternalNet name xc_top.tbcEnable is already in the DB.
WARNING (legacy-49196): Run 'emulatorConfiguration' command first.
INFO (legacy-42185): probeInternalNet name xc_top.sdlHaltHwClk is already in the DB.
WARNING (legacy-49196): Run 'emulatorConfiguration' command first.
INFO (legacy-42185): probeInternalNet name xc_top.hwClkDbg is already in the DB.
WARNING (legacy-49196): Run 'emulatorConfiguration' command first.
INFO (legacy-42185): probeInternalNet name xc_top.hwClkDbgTime is already in the DB.
WARNING (legacy-49196): Run 'emulatorConfiguration' command first.
INFO (legacy-42185): probeInternalNet name xc_top.hwClkEnable is already in the DB.
XEC> set compileScript "compile -names_crit"
compile -names_crit
XEC> set postCompileScript ""
XEC> 
XEC> handleBackendArgs $argc $argv
XEC> 
XEC> set defaultConfg [ file join $env(QTHOME) etc et3 ua_default.et3confg ]
/tools/cadence/UXE171_p98/tools.lnx86/etc/et3/ua_default.et3confg
XEC> emulatorConfiguration -add "file $defaultConfg" "boards 0.1"
/bin/cp -f /tools/cadence/UXE171_p98/tools.lnx86/etc/et3/ua_default.et3confg dbFiles/xcva_top.et3confg
XEC> 
XEC> if {[file exists xc_work/nl/hot-swap.qel]} {
    source xc_work/nl/hot-swap.qel
}
XEC> 
XEC> # Source compiler options script from user if specified
XEC> set compilerOptionsQel "xc_work/qel/compilerOptions.qel"
xc_work/qel/compilerOptions.qel
XEC> if { [file exists $compilerOptionsQel] } {
    source $compilerOptionsQel
} else {
    if {[file exists compilerOptions.qel]} {
	source compilerOptions.qel
    }
}
XEC> 
XEC> if {[info exists env(XE_DYNP)]} {
    compilerOption -add {visionMode DYNP}
} elseif {[info exists env(UXE_DYNP)]} {
    compilerOption -add {visionMode DYNP}
}
XEC> 
XEC> 
XEC> if {[info exists env(XE_MINSTEP)]} {
  eval "compilerOption -add {minStep $env(XE_MINSTEP)}"
} elseif  {[info exists env(UXE_MINSTEP)]} {
  eval "compilerOption -add {minStep $env(UXE_MINSTEP)}"
}
XEC> 
XEC> 
XEC> checkEnvForHostSetup
Environment variables found for emulator configuration.
emulatorConfiguration -add {host /tools/cadence/UXE171_p98/tools.lnx86} {boards 0.0}
WARNING (legacy-0): Can't resolve remote hostname 
/usr/bin/rcp /tools/cadence/UXE171_p98/tools.lnx86:/et3mach//tools/cadence/UXE171_p98/tools.lnx86.et3confg \
dbFiles/xcva_top.et3confg
ERROR (legacy-49382): Cannot copy \
'/tools/cadence/UXE171_p98/tools.lnx86:/et3mach//tools/cadence/UXE171_p98/tools.lnx86.et3confg': ÿÿ.
ERROR (legacy-43702): Failed to add emulator configuration.

    while executing
"emulatorConfiguration -add {host /tools/cadence/UXE171_p98/tools.lnx86} {boards 0.0}"
    ("eval" body line 1)
    invoked from within
"eval $cfgcmd "
    (procedure "checkEnvForHostSetup" line 35)
    invoked from within
"checkEnvForHostSetup"
    (file "/tools/cadence/UXE171_p98/tools.lnx86/etc/qel/ixcom.qel" line 140)
## xeCompile exits at 03/07/2020 16:41:42 Status: 1, PID: 153901
## xeCompile Elapsed time: 0:00:08, CPU time: 0:00:00.30, Memory Usage: 1.5G
## Child Proc. CPU time: 0:00:00.55
